### ISSUE TITLE
Astro 5 Support

### ISSUE THREAD

**Issue by imattdunbar** [storyblok/storyblok-astro#1010]
### Description

Creating this ticket since Astro 5.0 has been released and when upgrading this package makes you force install since the required dependency for astro is ^3.0.0 or ^4.0.0.

### Suggested solution or improvement

Add Astro ^5.0.0 to the ^3.0.0 || ^4.0.0 dependency here: https://github.com/storyblok/storyblok-astro/blob/02cf1f14bbf6f546a6f13f0f5b7666ccb0c728e3/lib/package.json#L71

### Additional context

Everything seems to be working fine even when I force install, haven't seen any issues yet so should be a relativey simple upgrade process

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client#code-of-conduct)

**Comment by Soviut** [comment]
This is pretty important on platforms like Cloudflare Pages since you can't override the `npm install` step.

**Comment by JayBox325** [comment]
Keen for this to get updated as I'm building an astro 5.0 project and I'm interested in trying Storyblok with it.

**Comment by Soviut** [comment]
@JayBox325 I worked around it by using `overrides` in my package.json.

```json
  "overrides": {
    "@storyblok/astro": {
      "astro": "$astro"
    },
    "@astrojs/cloudflare": {
      "astro": "$astro"
    }
  }
```

The `$astro` means use whatever version is currently installed as if it were the correct version.
