### ISSUE TITLE
Error after upgrading to Astro 5 

### ISSUE THREAD

**Issue by MrJonoCES** [storyblok/storyblok-astro#1040]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

---

## Expected Behavior

```
import { useStoryblokApi } from "@storyblok/astro";

const baseData = (async () => {
  const storyblokApi = useStoryblokApi();
  try {
    const { data } = await storyblokApi.get("cdn/stories/site-data/site-data", {
      version: "published",
    });

    console.log("data", data);
    const content = data.story.content;
    return {
      title: content.title,
      description: content.Description,
      image: content.ogImage.filename,
      imageAlt: content.ogImage.alt,
      bio: content.bio,
    };
  } catch (error) {
    console.error("Error fetching site data:", error.message);
    console.error("Status:", error.status);
    console.error("Response:", error.response);
  }
})();

export { baseData };
```

This code was successfully return the story data before the upgrade

## Current Behavior

Errors below are causing the build to fail
```
Error: storyblokApiInstance has not been initialized correctly
    at zn (.../NM/node_modules/@storyblok/astro/dist/storyblok-astro.es.js:1182:11)
    at eval (.../NM/src/data/siteData.js:7:65)
    at eval (...NM/src/data/siteData.js:35:3)
```

## Steps to Reproduce

Installed the following packages

```
    "@storyblok/astro": "^5.1.0",
    "@storyblok/react": "^3.0.11",
    "astro": "^5.0.9",
```

**Comment by dipankarmaikap** [comment]
@MrJonoCES Could you provide a minimal code example for me to test? I tried your code on the `@storyblok/astro` SDK with the package version you mentioned, along with your `baseData` code, and it seems to work fine.  

However, I’d like to highlight that there’s currently a bug related to types in the latest SDK release. This issue will be fixed shortly—I’ve already created a PR for it.  

Looking forward to your test case to investigate further!

**Comment by MrJonoCES** [comment]
@dipankarmaikap thanks for your help. I went through the update process on a couple other sites using the exact same baseData setup and they work fine so I think the problem lies elsewhere. The only thing different in this project is that one component uses react but that's totally unrelated to this component. Back to the drawing board
