### ISSUE TITLE
🐞 [BUG] There is a potential bug in using the function `useStoryblok` to get data in `livePreview: true` mode

### ISSUE THREAD

**Issue by JakiChen** [storyblok/storyblok-astro#1047]
### Describe the issue you're facing

e.g: when you edit the homepage in real time in the visual editor (it really works), but when you edit the [...] .astro file, the rendered page will not be consistent with your edits.

**Figure 1**: Visual editor: livePreview
<img width="1440" alt="截屏2024-12-30 11 07 10" src="https://github.com/user-attachments/assets/57ae584b-42dd-43ad-a1e7-49d9f68c82e0" />

**Figure 2**: [...slug].astro after being modified
<img width="1440" alt="截屏2024-12-30 11 05 01" src="https://github.com/user-attachments/assets/2a396fed-429c-4bd2-b8d9-112946d85b7a" />

> [!CAUTION]
> The data obtained after modifying `[...slug].astro` is still a **version from a long time ago**. 

### Reproduction

Please refer to [playgound/ssr](https://github.com/storyblok/storyblok-astro/tree/main/playground/ssr)

### System Info

```shell
Astro                    v5.0.9
Node                     v20.18.0
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/vercel
Integrations             @astrojs/svelte
                         @astrojs/vue
                         @astrojs/react
                         @storyblok/astro
                         @astrojs/tailwind
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by manuelschroederdev** [comment]
Hey @JakiChen, thank you for reporting this. In most real-world scenarios, content editors would use a dedicated, deployed preview environment that is not undergoing code changes while content is being edited. 🙂
Please note that `useStoryblok` will be deprecated fairly soon in favor of the new `getLiveStory` function. Stay tuned for the release and announcement.
