### ISSUE TITLE
StoryblokComponent is undefined

### ISSUE THREAD

**Issue by mariuscdejong** [storyblok/storyblok-astro#11]
I'm running into some problems with implementing this Astro module.

When trying to load the StoryblokComponent it says (see screenshot):
`Module '"/Users/xxx/Sites/xxx/node_modules/@storyblok/astro/StoryblokComponent.astro"' has no default export.`

<img width="1277" alt="Schermafbeelding 2022-09-07 om 15 24 48" src="https://user-images.githubusercontent.com/36531760/188889847-3319b202-481c-4586-980c-7f447b385939.png">

This results in this when I start the dev server (not sure if it is related):
<img width="921" alt="Schermafbeelding 2022-09-07 om 15 25 49" src="https://user-images.githubusercontent.com/36531760/188889879-7bdbdd6d-f628-4aad-82a5-8b54955c397f.png">

For all my Storyblok components are created into Astro components and linked in the config file.

"@storyblok/astro": "^1.0.0",

**Comment by manuelschroederdev** [comment]
Hey @mariuscdejong, 

could you please share your `astro.config.mjs`? Could you please double-check how you registered your component(s) there? I suspect that either the technical name from Storyblok or the file name of the Astro component doesn't match.

**Comment by mamunonweb** [comment]
I think it's the download demo from,

https://stackblitz.com/edit/astro-sdk-demo

**Comment by mariuscdejong** [comment]
<img width="1090" alt="Schermafbeelding 2022-09-13 om 08 53 16" src="https://user-images.githubusercontent.com/36531760/189831569-70f526b3-f725-43cf-87b2-e035b1d2fb82.png">

<img width="885" alt="Schermafbeelding 2022-09-13 om 08 57 04" src="https://user-images.githubusercontent.com/36531760/189831917-5e54541d-1b63-4d19-ae6d-10d2389fe6d5.png">

This is how my components and astro config are setup.

**Comment by mamunonweb** [comment]
Hi @manuelschroederdev,

Removing the extra surrounding curly `{}` seems will solve this problem. Just an Astro thingy.

https://github.com/storyblok/storyblok-astro/blob/a6a3dd58ff437d9ce4f3ebdf14c8d310c7769a88/lib/StoryblokComponent.astro#L8

**Comment by mariuscdejong** [comment]
Ah I had the extra quotes around `{blok}` in `<StoryblokComponent blok={blok} />`
Guess I copied that from the readme, already a PR open https://github.com/storyblok/storyblok-astro/pull/15

**Comment by mamunonweb** [comment]
@mariuscdejong 

But, I think that will not solve the **red squiggly** issue, or does it?

![Red squiggly](https://user-images.githubusercontent.com/36531760/188889847-3319b202-481c-4586-980c-7f447b385939.png)

**Comment by mariuscdejong** [comment]
@mamunonweb That's right, VS-code still gives the no default export error.

I can confirm that removing the extra surrounding curly braces seems to solve that.
