### ISSUE TITLE
Module '"@storyblok/astro"' has no exported member 'useStoryblokApi'.

### ISSUE THREAD

**Issue by simonhermann** [storyblok/storyblok-astro#17]
Setting up a fresh project with TS and following the guide, i get this error message in VSCode.

> Module '"@storyblok/astro"' has no exported member 'useStoryblokApi'.

The corresponding file `node_modules/@astro/dist/storyblok-astro.js` looks very broken when opening it, there seems to be an issue with minification.

**Comment by manuelschroederdev** [comment]
Hi @simonhermann,

thanks for pointing this out. We'll add TS support to the module soon and I'll have a look at the minification.

**Comment by ricardoaguiar** [comment]
It also fails when trying to run a local build with the stackblitz repo: 
<img width="1008" alt="Screenshot 2022-09-18 at 9 12 17 PM" src="https://user-images.githubusercontent.com/2197501/190924460-34add5f3-491a-4911-bdf7-e4917ce5a57d.png">

**Comment by ricardoaguiar** [comment]
The stackblitz repo also fails to generate a local build:
<img width="769" alt="Screenshot 2022-09-18 at 9 14 04 PM" src="https://user-images.githubusercontent.com/2197501/190924719-aa801a91-6f12-4a66-844c-219ae0b72233.png">

**Comment by manuelschroederdev** [comment]
Thanks for pointing that out @ricardoaguiar! Fixed.

**Comment by lukasholzer** [comment]
Yea sadly this library does not ship types to avoid this you can shim them on your own by adding to your `env.d.ts`


```typescript

declare module '@storyblok/astro' {
  type StoryblokAPI = {
  get: <Data>(
    path: string,
    options?: {
      starts_with?: string;
      version?: 'draft';
    },
  ) => { data: Data };

  export const useStoryblokApi: () => StoryblokAPI;
  export const renderRichText: (string: string) => any;
  export const storyblokEditable: (blok: any) => any[];
}

````

I hope they add some types soon. In general, that's the thing that annoys me the most as a storyblok developer to have always lacking type support 😢

**Comment by manuelschroederdev** [comment]
Sorry about that, full TypeScript support is going to come asap.

**Comment by Soviut** [comment]
@lukasholzer I was getting a parsing error with your shim. It seems you forgot an `}` to close the `type StoryblokAPI`.

For posterity, here's my fix.

```typescript
declare module '@storyblok/astro' {
  type StoryblokAPI = {
    get: <Data>(
      path: string,
      options?: {
        starts_with?: string;
        version?: 'draft';
      },
    ) => { data: Data };
  }

  export const useStoryblokApi: () => StoryblokAPI;
  export const renderRichText: (string: string) => any;
  export const storyblokEditable: (blok: any) => any[];
}
```

**Comment by ridem** [comment]
Here's a complete version that completely takes into account what's actually exported by the library, with the types provided by `@storyblok/js`:

```ts
/** See https://github.com/storyblok/storyblok-astro/blob/main/lib/index.js */
declare module "@storyblok/astro" {
  import {
    StoryblokClient,
    renderRichText as origRenderRichText,
    SbSDKOptions,
  } from "@storyblok/js";
  import { AstroIntegration } from "astro";

  export {
    storyblokEditable,
    loadStoryblokBridge,
    RichTextSchema,
  } from "@storyblok/js";

  export const useStoryblokApi: () => StoryblokClient;

  type SbRenderRichTextParams = Parameters<typeof origRenderRichText>;
  export const renderRichText: (
    data: SbRenderRichTextParams[0],
    options?: SbRenderRichTextParams[1]
  ) => ReturnType<typeof origRenderRichText>;

  interface IntegrationOptions
    extends Pick<
      SbSDKOptions,
      "accessToken" | "use" | "apiOptions" | "bridge"
    > {
    components: Record<string, string>;
  }

  const storyblokIntegration: (options: IntegrationOptions) => AstroIntegration;
  export default storyblokIntegration;
}
```
