### ISSUE TITLE
Text color gets applied as the background color for the RichText field when using renderRichText()

### ISSUE THREAD

**Issue by klib19** [storyblok/storyblok-astro#187]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

When I add a RichText field to a blok in my story, the "text color" setting is being applied as a `background-color` in CSS instead of `color`.

---

## Expected Behavior

The text color should be set as inline CSS

**What should be rendered as the html output:**
```
<p><span style="color:#AF1B1B">Hello World</span></p>
```

## Current Behavior

The background color is being set as inline CSS

**What is rendered as the html output:**
```
<p><span style="background-color:#AF1B1B">Hello World</span></p>
```

## Steps to Reproduce

1. Add a richText field to a blok in your story
2. Add the text "Hello World" to the richText field
3. Select that text and set the text color in the richText editor to red.
4. Follow the get started guide instructions to use the richText field => renderRichText()

**My astro file:**
```
---
import { storyblokEditable, renderRichText } from "@storyblok/astro";

const { blok } = Astro.props;
const paragraph = renderRichText(blok.paragraph);
---

<Fragment {...storyblokEditable(blok)}>
    <Fragment set:html={paragraph} />
</Fragment>
```
5. Start your Astro app and see that the background-color is set instead of the text color

**Comment by manuelschroederdev** [comment]
Hey @klib19, thank you very much for opening the issue. 🙂
This will be fixed with the next release of `storyblok-js-client`, the team is already working on it:
https://github.com/storyblok/storyblok-js-client/pull/520

**Comment by klib19** [comment]
Great, thank you for the update @manuelschroederdev!
