### ISSUE TITLE
Improve error handling when StoryblokComponent blok gets wrong value

### ISSUE THREAD

**Issue by edv-ns** [storyblok/storyblok-astro#204]
## Context

When working with Storyblok blocks, and doing some data mingling in nested structures, it can happen that the developer would accidentally pass the wrong value to the StoryblokComponent.

## Expected Behaviour

The informative error is given in case StoryblokComponent blok prop is an `undefined` value. This can happen when the CMS defines array of blocks, but no blocks are actually added, thus API returns empty array. This might result in StoryblokComonent getting undefined value.

```
<StoryblokComponent blok={logo[]} />
```

## Current Behaviour

The following error is visible and the server crashes.
```js
file:///Users/.../node_modules/.pnpm/camelcase@7.0.1/node_modules/camelcase/index.js:58
                throw new TypeError('Expected the input to be `string | string[]`');
                      ^

TypeError: Expected the input to be `string | string[]`
    at Proxy.camelCase (file:///Users/.../node_modules/.pnpm/camelcase@7.0.1/node_modules/camelcase/index.js:58:9)
    at eval (/@fs/Users/.../node_modules/.pnpm/@storyblok+astro@2.2.1/node_modules/@storyblok/astro/StoryblokComponent.astro:17:42)
    ...
```

**Comment by edv-ns** [comment]
At least I was using the following in my custom `StoryblokComponent.astro` when there was no [built-in fallbacking](https://github.com/storyblok/storyblok-astro#using-fallback-components) possibilities:

```
if (!blok) {
  throw new Error(`Cannot render StoryblokComponent. 'blok' prop is undefined.`);
}

if (!blok.component) {
  throw new Error(
    `Cannot render StoryblokComponent. Missing 'component' field in blok:\n${JSON.stringify(
      blok,
      null,
      2
    )}`
  );
}
```

It would be cool to add those just right before the usage of `camelcase` package to have errors catched and handled.

NOTE: the `blok` might be big object so either some excerpt needed or probably some generic message can be used alternatively: `Cannot render StoryblokComponent. Missing 'component' field in blok object.`, but it is hard to debug to know where is the exact culprit.

Probably ideally it would be nice to have that excerpt of some 1000 chars:
```
if (!blok.component) {
  const excerptLength = 1000;
  const excerpt = JSON.stringify(blok, null, 2);
  throw new Error(
    `Cannot render StoryblokComponent. Missing 'component' field in blok.\n${excerpt.substring(
      0,
      excerptLength
    )}${excerpt.length > excerptLength ? '\n...' : ''}`
  );
}
```

**Comment by manuelschroederdev** [comment]
Thank you very much for opening this issue @edv-ns! 🙂
I'll look into it as soon as possible.

**Comment by edv-ns** [comment]
> Hey @edv-ns, in which scenarios would you receive a `blok` without a `component` field?

Hey, well, you might be right, it may hardly happen.. 🤔 Well, I was initially thinking about the situations when there is some extra data mingling and developer just accidently passing something unnexpected to `StoryblokComponent`. Even though there are types, they do not guarantee that the data is in expected shape, because of fetching happening on runtime, so technically anything can be returned.

As for the `!blok` situations it is pretty easy to get one:
- f.e. cms `logo: Blok[]` is empty and there is no "required" flag in CMS applied, thus empty array returned from API, that would break the app to try rendering `<StoryblokComponent blok={logo[0]} />`

Anyway, shall we drop this `!blok.component` situation handling for now? I cannot come up with a strong argument to back that.

**Comment by manuelschroederdev** [comment]
Thank you very much for the explanation. 🙂
I totally understand the `!blok` situation, handling that scenario more gracefully is a really nice improvement. Yes, I'd say let's drop the `!blok.component` handling for now, possibly something we can revisit in the future.

**Comment by edv-ns** [comment]
Agreed. I have updated the description accordingly to only cover `!blok` case. Hope this works fine for now!

**Comment by manuelschroederdev** [comment]
Thank you!
