### ISSUE TITLE
storyblokEditable still visible when bridge set to false

### ISSUE THREAD

**Issue by J05HI** [storyblok/storyblok-astro#278]
I've set Storyblock bridge to false.
In the generated html the data-blok-c and data-blok-uid is still visible.

**Comment by manuelschroederdev** [comment]
Hi @J05HI, thanks for your issue report. I cannot reproduce this behavior, could you please share a link to your deployed site or an other reproducible example?

**Comment by manuelschroederdev** [comment]
Please try getting the `published` version of your stories in `[...slug].astro`, that should do the trick. 🙂
