### ISSUE TITLE
missing StoryblokComponent.astro type declarations

### ISSUE THREAD

**Issue by dovydas0** [storyblok/storyblok-astro#352]
### Describe the issue you're facing

When building a page with Astro importing StoryblokComponent.astro component into .astro file gives back a type declaration error. However, other SDK's functions like "useStoryblokApi" are not giving any errors.

![image](https://github.com/storyblok/storyblok-astro/assets/76953231/da2b1799-a07d-43ff-b93b-93705e1313fc)

The Astro app is running even with an error and the StoryblokComponent is working. But ideally the error should not be there. I could not find any @types/ packages for the @storyblok/astro SDK. But if I go to /src/env.d.ts and provide this line of code: "declare module '@storyblok/astro/StoryblokComponent.astro';" the type error goes away.

### Reproduction

https://github.com/doovis/storyblok-bug/blob/master/src/pages/index.astro

### Steps to reproduce

Just opening up /src/pages/index.astro should show the error on the "StoryblokComponent" import line.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.10 GB / 7.88 GB
Binaries:
    Node: 19.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.79)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by manuelschroederdev** [comment]
Hey @doovis,

thanks for reporting this bug. However, I cannot reproduce this behavior, neither in your example nor any other project. Are you still facing this issue?

**Comment by Nish17g** [comment]
Hello @manuelschroederdev , I am able to reproduce a similar issue with @storyblok/astro package .Screenshot below 
<img width="1250" alt="image" src="https://github.com/storyblok/storyblok-astro/assets/50920962/917ff97e-4f40-4c48-a1e4-de5ee57c2181">
Astro build also fails with the same issue.Error message below.
#0 5.771 [vite-plugin-storyblok-components] Could not load virtual:storyblok-components (imported by node_modules/@storyblok/astro/StoryblokComponent.astro): Component could not be found for blok "insiders"! Does "/src/contents/blogInsiders/Insider.astro" exist?
#0 6.197  error   Could not load virtual:storyblok-components (imported by node_modules/@storyblok/astro/StoryblokComponent.astro): Component could not be found for blok "insiders"! Does "/src/contents/blogInsiders/Insider.astro" exist?

**Comment by vcotir** [comment]
Same. Virtual modules are unimported? 
<img width="768" alt="image" src="https://github.com/storyblok/storyblok-astro/assets/20938052/e0b6b97c-7f38-40cf-bd5c-ddcdd2bf004b">

**Comment by thejackshelton** [comment]
I have the same issue as well. It's this virtual module.

Also get another type error on blok.component

```
/**
 * convert blok components to camel case to match vite-plugin-storyblok-components
 */
let key = camelcase(blok.component);
```

```tsx
Argument of type 'string | undefined' is not assignable to parameter of type 'string | readonly string[]'.
  Type 'undefined' is not assignable to type 'string | readonly string[]'.ts(2345)
```

**Comment by thejackshelton** [comment]
I made a PR for the latter:

https://github.com/storyblok/storyblok-astro/pull/414

**Comment by leimeter-joaquin** [comment]
I am facing the same issue. I don't think I am experienced enough to be of any help but I ma getting the same error with the virtual modules not being found in the StoryblokComponent definition inside node_modules/@storyblok/astro/StoryblokComponent.astro.
<img width="927" alt="Screenshot 2023-09-01 at 13 13 31" src="https://github.com/storyblok/storyblok-astro/assets/53354878/626870e4-e12a-4eb8-b7db-fd5dc0c91135">

**Comment by Britnell** [comment]
Hey, second this, have the exact same error 
![grafik](https://github.com/storyblok/storyblok-astro/assets/19732260/a8436730-4f8e-4379-aa4c-e683fc642e37)
![grafik](https://github.com/storyblok/storyblok-astro/assets/19732260/419cdf8e-0e34-4e71-8f61-cb5dd4d61680)

i am following the [astro guide](https://docs.astro.build/en/guides/cms/storyblok/)
& have the package installed

```
{
  "name": "test",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@storyblok/astro": "^3.0.0",
    "astro": "^3.0.11",
    "storyblok-js-client": "^6.0.0",
    "vite": "^4.4.9"
  }
}

```

**Comment by F0rce** [comment]
I am getting the exact same error like @Britnell with the exact same dependencies.

**Comment by shixish** [comment]
I'm on version 3.0.1 and I'm still seeing this error message. It appears to work anyway however. 🤷

![image](https://github.com/storyblok/storyblok-astro/assets/371377/a34d1592-80de-48ee-b7dc-d24020d1affb)

**Comment by manuelschroederdev** [comment]
Hey @shixish, thanks for sharing. That's weird and I cannot reproduce it. Could you please share a minimal reproducible example?

**Comment by shixish** [comment]
@manuelschroederdev I put together a minimal setup here: 
https://github.com/shixish/minimal-astro-storyblok/

The issue can be seen in both of these files:
- https://github.com/shixish/minimal-astro-storyblok/blob/main/src/pages/index.astro
- https://github.com/shixish/minimal-astro-storyblok/blob/main/src/storyblok/Page.astro

I tried out this new repo with my Storyblok preview token and this repo appears to work. 👍

**Comment by stvnfox** [comment]
I'm currently having an error similar like above where camelcase is giving a type error:
![image](https://github.com/storyblok/storyblok-astro/assets/38129168/00988871-977f-41b5-b63d-f9c1c716f32a)
`TypeError: Expected the input to be `string | string[]`
    at Module.camelCase (file:///C:/Projecten/website-stvn/node_modules/.pnpm/camelcase@8.0.0/node_modules/camelcase/index.js:59:9)
    at C:\Projecten\website-stvn\node_modules\.pnpm\@storyblok+astro@3.1.0-next.3_astro@4.0.6\node_modules\@storyblok\astro\components\StoryblokComponent.astro:24:11
    at AstroComponentInstance.StoryblokComponent [as factory] (C:\Projecten\website-stvn\node_modules\.pnpm\astro@4.0.6_typescript@5.3.3\node_modules\astro\dist\runtime\server\astro-component.js:18:12)
    at AstroComponentInstance.init (C:\Projecten\website-stvn\node_modules\.pnpm\astro@4.0.6_typescript@5.3.3\node_modules\astro\dist\runtime\server\render\astro\instance.js:33:29)
    at AstroComponentInstance.render (C:\Projecten\website-stvn\node_modules\.pnpm\astro@4.0.6_typescript@5.3.3\node_modules\astro\dist\runtime\server\render\astro\instance.js:38:18)
    at Object.render (C:\Projecten\website-stvn\node_modules\.pnpm\astro@4.0.6_typescript@5.3.3\node_modules\astro\dist\runtime\server\render\component.js:328:22)
    at Module.renderChild (C:\Projecten\website-stvn\node_modules\.pnpm\astro@4.0.6_typescript@5.3.3\node_modules\astro\dist\runtime\server\render\any.js:29:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

I'm on node 21.3.0 using pnpm and tried out every version of the storyblok-astro package but having this issue on every version.

Package.json file:
![image](https://github.com/storyblok/storyblok-astro/assets/38129168/ddc83875-ab21-4b14-a980-f0ee9f201aea)

**Comment by davidha99** [comment]
I see the same error shared by @shixish and @Britnell on version ^4.0.0. I'm following the example from [Storyblok & Astro integration docs].(https://docs.astro.build/en/guides/cms/storyblok/#fetching-data)

`test-post.astro`
![image](https://github.com/storyblok/storyblok-astro/assets/52906616/c5495524-673c-4fbc-b3ef-e0258b9ed48b)

`astro.config.mjs`
![image](https://github.com/storyblok/storyblok-astro/assets/52906616/37ced31c-28e4-48ff-a150-41c07e5edd61)

**Comment by schabibi1** [comment]
Thanks everyone for reporting.
Could you all try with @storyblok/astro 4.0.3? This version should fix the issue, as I tested and it worked.
> Related issue #637

Feel free to re-open this issue if you face a similar case.

**Comment by andriy-rymar-jappware** [comment]
Hi guys! Faced with the same issue with type declaration for StoryblokComponent. I update the Astro js to version 5.0.4 and @storyblok/astro  to 5.1.0

How fix this annoying error?

import StoryblokComponent from "@storyblok/astro/StoryblokComponent.astro"; 

TS error **Cannot find module '@storyblok/astro/StoryblokComponent.astro' or its corresponding type declarations.**
 "astro": "5.0.4"  "@storyblok/astro": "^5.1.0",

"dependencies": {
    "@astrojs/netlify": "^6.0.1",
    "@astrojs/sitemap": "3.2.1",
    "@astrojs/tailwind": "5.1.3",
    "@astrojs/upgrade": "^0.4.2",
    "@astrojs/vue": "^5.0.1",
    "@lottiefiles/lottie-player": "^2.0.2",
    "@popperjs/core": "^2.11.8",
    "@storyblok/astro": "^5.1.0",
    "@vitejs/plugin-basic-ssl": "1.2.0",
    "ansi-align": "3.0.1",
    "astro": "5.0.4",
    "string-width": "^4.2.3",
    "string-width-cjs": "^5.1.1",
    "swiper": "11.1.15",
    "tailwindcss": "3.4.16",
    "vue": "3.5.13"
  },
  "devDependencies": {
    "prettier": "3.4.2",
    "prettier-plugin-astro": "^0.14.1",
    "prettier-plugin-tailwindcss": "^0.6.9",
    "typescript": "^5.7.2",
    "vite": "^6.0.3"
  },
  "resolutions": {
    "strip-ansi": "^6.0.1",
    "string-width": "^4.2.3"
  }
<img width="1448" alt="Знімок екрана 2024-12-20 о 13 10 28" src="https://github.com/user-attachments/assets/5edfd50c-17c5-48b2-94ef-3c95937bc5b6" />


tsconfig.json

{
  "extends": "astro/tsconfigs/base",
  "include": [".astro/types.d.ts", "**/*"],
  "exclude": ["dist"],
  "compilerOptions": {
    "strict": true,
    "target": "ESNext",
    "module": "ESNext",
    "lib": ["dom", "dom.iterable"],
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "baseUrl": ".",
    "types": ["astro/client"],
    "jsx": "preserve"
  }
}

**Comment by ybabenkoJapp** [comment]
Hi! I updated Astro js to 5.0.4 and @storyblok/astro to 5.1.0. Now I have such annoying ts error.  How to fix it? Thanks you for your help

import StoryblokComponent from "@storyblok/astro/StoryblokComponent.astro";
**Cannot find module '@storyblok/astro/StoryblokComponent.astro' or its corresponding type declarations.
  There are types at '/Users/ybabenko/WebstormProjects/project-name/node_modules/@storyblok/astro/dist/components/StoryblokComponent.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(2307)**
  
node version v18.20.4
macOS sequoia 15.1.1
deps
 "dependencies": {
    "@astrojs/netlify": "^6.0.1",
    "@astrojs/sitemap": "3.2.1",
    "@astrojs/tailwind": "5.1.3",
    "@astrojs/upgrade": "^0.4.2",
    "@astrojs/vue": "^5.0.1",
    "@lottiefiles/lottie-player": "^2.0.2",
    "@popperjs/core": "^2.11.8",
    "@storyblok/astro": "^5.1.0",
    "@vitejs/plugin-basic-ssl": "1.2.0",
    "ansi-align": "3.0.1",
    "astro": "5.0.4",
    "string-width": "^4.2.3",
    "string-width-cjs": "^5.1.1",
    "swiper": "11.1.15",
    "tailwindcss": "3.4.16",
    "vue": "3.5.13"
  },
  "devDependencies": {
    "prettier": "3.4.2",
    "prettier-plugin-astro": "^0.14.1",
    "prettier-plugin-tailwindcss": "^0.6.9",
    "typescript": "^5.7.2",
    "vite": "^6.0.3"
  },
  "resolutions": {
    "strip-ansi": "^6.0.1",
    "string-width": "^4.2.3"
  }

tsconfig.json

{
  "extends": "astro/tsconfigs/base",
  "include": [".astro/types.d.ts", "**/*"],
  "exclude": ["dist"],
  "compilerOptions": {
    "strict": true,
    "target": "ESNext",
    "module": "ESNext",
    "lib": ["dom", "dom.iterable"],
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "baseUrl": ".",
    "types": ["astro/client"],
    "paths": {
      "@/*": ["src/*"]
    },
    "jsx": "preserve"
  }
}

<img width="1448" alt="Знімок екрана 2024-12-20 о 13 10 28" src="https://github.com/user-attachments/assets/97d4387a-a1f6-4b39-9782-6e01f449226c" />

**Comment by F0rce** [comment]
@ybabenkoJapp probably related to #1033 - or better said that's the new issue for it
