### ISSUE TITLE
how to handle edit mode with previewToken / publicToken

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-astro#36]
Hi

I'm intrigued to try out astro. How would I properly handle the preview / public token ? Currently I see that the docs state to provide the preview token, but that should only be the case for the editable mode? Would it not make sense to split the accessToken up to `previewToken` / `publicToken`?

**Comment by manuelschroederdev** [comment]
Hey @dohomi, if you add the token as an environment variable, you can simply provide the preview token in your preview/development environment and the public token in the production environment.

Example:

```javascript
import { defineConfig } from 'astro/config'
import * as dotenv from 'dotenv'
dotenv.config()
import storyblok from '@storyblok/astro'

export default defineConfig({
  integrations: [
    storyblok({
      accessToken: process.env.STORYBLOK_TOKEN,
    }),
  ],
})
```

**Comment by dohomi** [comment]
@manuelschroederdev isn't the access token determined if you are working inside of the Storyblok backend? You suggest that users should wire up 2 environments, one deployed with preview for Storyblok access and one for the frontend only?

**Comment by manuelschroederdev** [comment]
The preview token provides access to saved/draft and published stories, whereas the public token provides access to published stories only. In a typical setup, you would use the preview token for your preview environment (could be your local dev server or deployed somewhere) and the public token for your live/production environment.

I hope that helps clear things up, let me know if need any further help with this. 🙂

**Comment by dohomi** [comment]
In my NextJS projects I swop the preview/public token based on the preview cookie. Is there something similar in Astro?

**Comment by manuelschroederdev** [comment]
Preview cookie...do you mean using the URL parameter to detect whether you're in the Visual Editor? If so, you could do that to determine whether the `draft` or `published` version of the story should be requested.

Regarding the tokens, I would always suggest setting them via environment variables.

**Comment by edv-ns** [comment]
I went with explicit config partials:

```
const configPreview = {
  accessToken: process.env.STORYBLOK_TOKEN_PREVIEW,
  bridge: true,
};

const configPublic = {
  accessToken: process.env.STORYBLOK_TOKEN_PUBLIC,
  bridge: false,
};

export default defineConfig({
  integrations: [
    storyblok({
      ...(process.env.STORYBLOK_PREVIEW_ENABLED === 'true' ? configPreview : configPublic),
      // other configurations
    }),
  ],
})
```

as it seemed more staight-forward for me to hook logic into a single variable to switch app between preview and public modes.

NOTE: it is super important to pass `bridge: false,` to exclude storyblok bridge script from public(production) build because it is [activated by default](https://github.com/storyblok/storyblok-astro#using-the-storyblok-bridge:~:text=The%20Storyblok%20Bridge%20is%20automatically%20activated%20by%20default). I have[ raised another discussion](https://github.com/storyblok/storyblok-astro/issues/48) to maybe have it disabled by default, so it does not slip to production by accident.
