### ISSUE TITLE
Components added in Storyblok but not in the code will trigger an error

### ISSUE THREAD

**Issue by vladtbb** [storyblok/storyblok-astro#37]
Currently there is no way for @storyblok/astro to ignore unbuilt blocks. This makes it harder for the client and the developer when moving/creating blocks.

Example: You have blocks 1,2,3 in storyblok, but only blocks 1 and 3 in your code. The whole build will fail.

Fix suggestion: A bonus conditional to the logic for pulling blocks so either the blocks that don't exist in the codebase yet are ignore or we can have an alternative block such as a placeholder. The placeholder method would be ideal for me and the organisation I'm working for, probably for most people too!

Please let me know if this is unclear and I'll try and provide some more info!

**Comment by joezimjs** [comment]
I'm not a contributor on this project or anything, but my thoughts on this is that in many cases you would want that error so you know quickly from looking at the logs that you have something wrong. Although, if you can still leave the build/render errors in the console while putting in the placeholders, that would probably be useful.

**Comment by edv-ns** [comment]
I am pretty sure it would be logical to show some placeholder if any unknown component is in the list to process, so when `bridge` is enabled content editors would see that it is not yet developed.

NOTE: we might not render such placeholder if it is production build. It could simply omit it so end users would not see it.

**Comment by edv-ns** [comment]
I might use custom implementation of `StoryblokComponent` for now:

```
---
import components from 'virtual:storyblok-components';
const { blok, ...props } = Astro.props;

const Component = components[blok.component];
---

{
  Component ? (
    <Component blok={blok} {...props} />
  ) : (
    <div>The component {blok.component} is not yet implemented</div>
  )
}
```

**Comment by vladtbb** [comment]
This is a great solution @edv-ns but this will only work for when you're working locally since the storyblok-astro NPM package is "as-is" when the code goes live (in my case it goes to Netlify and renders the site), meaning the change you're suggesting won't get pushed live unless we specify an override of node_modules, which is not a good idea.

Maybe this can be turned into a pull request? I like the idea of specifying the `undefined` component as a custom block, but it would be also nice to have a default out-of-the box placeholder from the module itself, which we can then override if needed.

I see you've pretty much summarised the above in your previous comment:


> I am pretty sure it would be logical to show some placeholder if any unknown component is in the list to process, so when `bridge` is enabled content editors would see that it is not yet developed.
> 
> NOTE: we might not render such placeholder if it is production build. It could simply omit it so end users would not see it.


Currently the production build fails when a block is undefined, will your code stop the build from failing and just ignore the undefined blocks?

**Comment by edv-ns** [comment]
@vladtbb I barely started integrating this package to the project, so I might think of a solution to either fail build if some blok implementations missing or just completely skip rendering those component, so it does not slip to to the end users.

**Comment by joezimjs** [comment]
Is there a way to create a copy of StoryblokComponent in your own source code? I guess the real question is whether or not we can use a Vite plugin or something that allows us to import `"virtual:storyblok-components"` in our own code? If so, then we don't need to worry about deploying breaking anything and you can add a condition to check for dev/production to determine what to do there as well.

**Comment by edv-ns** [comment]
Yes @joezimjs, that is exactly what I did (for typescript `declare module 'virtual:storyblok-components';`).

Only the placeholder showing logic is kept in `Placeholder.astro` instead.

But yeah, these issues might need to be addressed in  this `storyblok-astro` package instead of doing custom workarounds (what if vite plugin changes its under-the-hood `virtual:storyblok-components` value 🙈 ? we might get lost easily)

**Comment by manuelschroederdev** [comment]
Thanks for the very interesting discussion and great ideas, everyone. :) 
We'll have a look at the different options soon and follow up here.

**Comment by joezimjs** [comment]
I don't see how that closes this issue. They are about 2 entirely separate issues.

**Comment by edv-ns** [comment]
Agree with @joezimjs, the issue was not solved, because of 2 reasons:

1. the app build will still fail if Storyblok pass the unknown component to render.
2. placeholder (unknown component indication) was not solved (just TODO added: https://github.com/storyblok/storyblok-astro/blob/main/lib/StoryblokComponent.astro#L15)

**Comment by joezimjs** [comment]
Technically, the placeholder is a suggested solution and the only thing that NEEDS to be done to _solve the issue_ is to not throw an error when the component doesn't exist, but yeah, allowing us to specify...

1. A component to use as a placeholder
2. Whether to show the placeholder on production (MIGHT be useful, but if nothing else, just always prevent it from showing on production and show nothing instead)
3. Whether to throw an error or show nothing if not using a placeholder

... would be a great solution.

**Comment by vladtbb** [comment]
Is there something we can do to speed up this being implemented? This is a very common issue that keeps popping up and messing our PRs/branches when building new components.

**Comment by edv-ns** [comment]
Yeah, this would be great to have solved.

For the time being, I just use custom `StoryblokComponent.astro` implementation in the project with
```
const Component = components[blok.component] || components?.placeholder;
```
and my own placeholder component implemented as a fallbacking. I hope we could use StoryblokComponent from the integration package once this task is solved 🙏

**Comment by vladtbb** [comment]
@edv-ns This is a great workaround for the time being. If the storyblok-astro developers don't have the time to implement their own solution this can work as a substitute if it's turned into a PR.

What do you think @manuelschroederdev
