### ISSUE TITLE
Refresh visual editor on save doesn't work on Vercel

### ISSUE THREAD

**Issue by MKlblangenois** [storyblok/storyblok-astro#397]
Preview isn't refreshed with new content inside visual editor when project is hosted on Vercel

---

## Expected Behavior
Data should updated when user hit "save" button

## Current Behavior
Data isn't updated and new page return an error 404 on visual editor. Hit the button "save" with localhost in visual editor trigger the reload has excepted

[Video reproduction](https://www.loom.com/share/5ef4e965af7d4e42a146a0fd24a64011?sid=75da4dbf-a9ee-47e0-a31c-37586d483b6f)

## Steps to Reproduce

1. Follow [the tutorial](https://www.storyblok.com/tp/the-storyblok-astro-ultimate-tutorial) to create a project using Storyblok with Astro
2. Add `vercel` adapter
3. Deploy to Vercel and add URL to your editor
4. Try to update content and save

```js
// astro.config.mjs

export default defineConfig({
	trailingSlash: "ignore",
	build: {
		format: "directory",
	},
	redirects: {
		"/formations/approches": "/formations",
		"/formations/themes": "/formations",
	},
	integrations: [
		tailwind(),
		storyblok({
			accessToken: "my-token",
			components,
			apiOptions: {
				region: "eu"
			},
			customFallbackComponent: "components/sections/sectionEmpty/index",
			enableFallbackComponent: true,
			bridge: true,
		}),
		react(),
	],
	experimental: {
		viewTransitions: true,
	},
	output: "server",
	adapter: vercel(),
});
```

**Comment by manuelschroederdev** [comment]
Hi @MKlblangenois,

I've just tried to reproduce this behavior, but in my tests, the Bridge works completely fine when using the Vercel Adapter for SSR.
Here's the example repository I used: https://github.com/manuelschroederdev/astro-vercel-adapter-test
Deployed here: https://sb-astro-vercel-adapter-test.vercel.app/

Regarding the 404s: did you create a catch-all route such as `[...slug].astro`? If not, the errors are expected.

**Comment by MKlblangenois** [comment]
Hey @manuelschroederdev

Thanks for your reproduction!

Yes, I've a `[folder]/[...path].astro` that should catch-all route, I've tried to set it as `[...slug].astro` on root of pages, but I got the same issue.

This is my code for `[...path].astro` :

```ts
export const getStaticPaths = async () => {
	const stories = await getAllStories();

	if (!stories) {
		return {
			notFound: true,
		};
	}

	const paths: any = [];

	stories.map((story: any) => {
		const avoided_full_slug = "formations/";
		if (!story.full_slug.startsWith(avoided_full_slug) || story.parent_id !== null) {
			const item = {
				params: {
					folder: story.full_slug.split("/")?.length > 0 ? story.full_slug.split("/")[0] : story.slug,
					path: story.is_startpage || story.full_slug.split("/")?.length <= 1 ? undefined : story.slug,
				},
				props: {
					full_slug: story.full_slug,
				},
			};
			paths.push(item);
		}
	});

	return paths;
};

const { folder, path } = Astro.params;

const story = await getStory([folder, path].filter((x) => x).join("/") || "home");

export const prerender = true;
```

```ts
/**
 * Get all Storyblok stories.
 *
 * Due to limit of 100 stories per request, we need to make a loop until there's no more stories.
 *
 * @param {ISbStoriesParams} [filters={}]
 * @return {any} The Storyblok stories.
 */
export const getAllStories = async (filters: ISbStoriesParams = {}) => {
	const params: ISbStoriesParams = {
		version: "draft",
		excluding_slugs: "site-settings,home,testimonials/*",
		cv: +new Date(),
		...filters,
	};

	try {
		const { data } = await client.get("cdn/stories", params);

		if (data?.stories) {
			let stories = data.stories;

			while (data?.links?.next_page) {
				params.page = data.links.next_page;

				const { data: nextData } = await client.get("cdn/stories", params);

				stories = [...stories, ...nextData.stories];
			}

			return stories;
		}
	} catch (error) {
		console.error(error);
	}

	return false;
};
```
> [!NOTE]
> `getStory` and `getAllStories` use both `useStoryblokApi()` and "draft" as version.
