### ISSUE TITLE
Fail to register Storyblok access token in Astro config from env variables

### ISSUE THREAD

**Issue by AnaelBonnafous** [storyblok/storyblok-astro#40]
Got error in CLI when registering access token in config file via process.env, whereas it works by directly typing the raw value :

```
storyblokApiInstance has not been initialized correctly
 error   Cannot read property 'get' of undefined
```

My astro.config.mjs file
```mjs
import { defineConfig } from "astro/config";
import storyblok from "@storyblok/astro";

// https://astro.build/config
export default defineConfig({
  integrations: [
    storyblok({
      /* Raw value: work
      accessToken: XXXXXXXXXXXXXXXXXXXXXXXX, */
      // Env variable: throw error
      accessToken: process.env.STORYBLOK_TOKEN,
      components: {
        feature: "storyblok/Feature",
        grid: "storyblok/Grid",
        page: "storyblok/Page",
        teaser: "storyblok/Teaser",
      },
    }),
  ],
});
```
My .env file
```
STORYBLOK_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXX
```

- astro: 1.3.1
- @storyblok/js: 1.8.5
- @storyblok/astro: 1.1.0

**Comment by preetamslot** [comment]
I had the same issue. if you read the docs:

> CAUTION
> import.meta.env and .env files are not available inside [configuration files]

So it's not a bug, its a feature :)

(https://docs.astro.build/en/guides/configuring-astro/#environment-variables).


https://docs.astro.build/en/guides/environment-variables/

**Comment by AnaelBonnafous** [comment]
Thanks for the reply and the link, I actually miss that :)

I saw this video from Matt Maribojoc and got inspired by his code, as you can see down below
(https://github.com/mattmaribojoc/mattmaribojoc.com/blob/main/astro.config.mjs#L12)
(https://youtu.be/viV0ROCVEO8?t=31)

Thought directly calling vars from .env file would do the trick.
But I actually manage to make it works with dotenv, do you have a preferred way ?
