### ISSUE TITLE
Render SB components inside Rich Text

### ISSUE THREAD

**Issue by joezimjs** [storyblok/storyblok-astro#44]
Your README show this:

```ts
import { RichTextSchema, renderRichText } from "@storyblok/astro";
import cloneDeep from "clone-deep";

const mySchema = cloneDeep(RichTextSchema); // you can make a copy of the default RichTextSchema
// ... and edit the nodes and marks, or add your own.
// Check the base RichTextSchema source here https://github.com/storyblok/storyblok-js-client/blob/master/source/schema.js

const { blok } = Astro.props

const renderedRichText = renderRichText(blok.text, {
  schema: mySchema,
  resolver: (component, blok) => {
    switch (component) {
      case "my-custom-component":
        return `<div class="my-component-class">${blok.text}</div>`;
        break;
      default:
        return `Component ${component} not found`;
    }
  },
});
```

But I want to know how I can get `renderRichText` to render `<StoryblokComponent blok={blok} />` for every component. 

If I do the following:

```tsx
const renderedRichText = renderRichText(blok.text, {
	schema: cloneDeep(RichTextSchema),
	resolver(component, blok) {
		return <StoryblokComponent blok={blok} />
	}
})
```

I see this:

```
ERROR: Expected ">" but found "blok"
  File:
    C:/localhost/astro-storyblok/src/components/bloks/Teaser.astro
  Code:
      10 |   resolver(component, blok) {
    > 11 |     return <StoryblokComponent blok={blok} />
         |                              ^
      12 |   }
      13 | })
```

I'm assuming you can't use "JSX" (or whatever Astro calls their version of the template language) in the script section at the top, so I'm not sure how to handle it. Is there a function I can import that will render a component, like `h` in React or something? e.g. the fictional `renderComponent` in this example:

```tsx
const renderedRichText = renderRichText(blok.text, {
	schema: cloneDeep(RichTextSchema),
	resolver(component, blok) {
		return renderComponent(`<StoryblokComponent blok={blok} />`)
	}
})
```

or more like `h`:

```tsx
const renderedRichText = renderRichText(blok.text, {
	schema: cloneDeep(RichTextSchema),
	resolver(component, blok) {
		return renderComponent(StoryblokComponent, {blok: blok})
	}
})
```

**Comment by zeddic** [comment]
I found a work around of manually iterating over the `blok.text` rich text field. This ends up being a list of structured objects, with `blok` types containing a list of child blocks within a `body` field. You can use this to conditionally send some child nodes to the `renderRichText` function and others to `<StoryblokComponent>`:

```jsx
{
    blok?.text?.content?.map((block) => {
      if (block.type === 'blok') {
        return block?.attrs?.body?.map((childBlock) => {
          return (
            <>
              <StoryblokComponent blok={childBlock} props={undefined} />
            </>
          );
        });
      } else {
        return (
          <>
            <Fragment set:html={renderRichText({content: [block]})} />
          </>
        );
      }
    })
  }
```

For reuse, this could be wrapped in a AstroComponent that you reuse whenever you want to show rich text content with support for nested bloks.

**Comment by brvnonascimento** [comment]
Easiest solution for me was just using a regular function that returns a template string and use this [syntax highlighting extension](https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html)

```ts
// storyblok/atoms/CTAButton.ts
import { CtaButtonStoryblok } from "@types";

export const CTAButton = (blok: CtaButtonStoryblok) => {
  const link = blok?.link?.[0];

  return link ? /* html */ `<a>${link.title}</a>` : null;
};
```

and on then call it in renderRichText:

```ts
  renderRichText(blok.content, {
      resolver: (component, blok) => {
        switch (component) {
          case "ctaButton":
            return CTAButton(blok);
          default:
            return null;
        }
      },
    })
```
Not ideal but works for now. Although you can't reuse this component inside other `.astro` components and need to keep a different `.astro` copy of the `.ts` component for that.

**Comment by brvnonascimento** [comment]
You also need to write global CSS to style that.

**Comment by marsidev** [comment]
35e208c6142b39771edfbc8831934ccccaf010a5 ([v2.4.0](https://github.com/storyblok/storyblok-astro/compare/v2.3.5...v2.4.0)) introduced a `<RichTextRenderer />` component to render blocks inside a rich text:

```astro
---
import { renderRichText, RichTextRenderer } from '@storyblok/astro';
const { blok } = Astro.props
---

<RichTextRenderer richTextData={blok.richtext} />
```

I think this issue can be closed.

**Comment by joezimjs** [comment]
Just like [my comment earlier](https://github.com/storyblok/storyblok-astro/issues/44#issuecomment-1353783567) about the solution listed above: this solution will only render bloks at the root level. If a blok is embedded inside another node, e.g. a list item, it will not work. I don't know how common that might be, but I can guarantee it's not 0% of bloks inside rich text and if someone wants to have one embedded deeper, it's generally for a very good reason.

You're going to have to stop relying on the `renderRichText` function that you get from @storyblok/js. See what I did for my Nuxt project: https://github.com/storyblok/storyblok-nuxt/issues/476#issuecomment-1628149089. You'll need to parse through the rich text data yourself, converting the nodes/marks to JSX rather than just building an HTML string.

**Comment by joezimjs** [comment]
I've actually updated my Nuxt implementation (still needs a little more work), as you can see here: https://github.com/storyblok/storyblok-nuxt/issues/476#issuecomment-1631952576

**Comment by manuelschroederdev** [comment]
Hey all, I'm happy to share that this is possible using the amazing [storyblok-rich-text-astro-renderer](https://www.npmjs.com/package/storyblok-rich-text-astro-renderer) provided by @edv-ns. 🙂
