### ISSUE TITLE
StackBlitz live demo doesn't work

### ISSUE THREAD

**Issue by belarusaed** [storyblok/storyblok-astro#451]
## Expected Behavior

When I click [live dome](https://stackblitz.com/edit/astro-sdk-demo) from the README, I except demo project to run normally.

## Current Behavior

Live demo doesn't work because Astro dropped node 16 support and StackBlitz use node 16

## Steps to Reproduce

1. Navigate to the demo project on StackBlitz from README

**Comment by manuelschroederdev** [comment]
Hey @belarusaed, thank you for reporting that. We're aware of the issue. Since Astro 3.0 requires Node 18, there's not much we can do but wait at this point.
