### ISSUE TITLE
Add option to configure loading of storyblok bridge conditionally based on _storyblok query parameter

### ISSUE THREAD

**Issue by dominik-erni** [storyblok/storyblok-astro#472]
### Description

In our Astro SSR frontend, we want the storyblok bridge only be loaded when the content is displayed in the preview iframe within storyblok. Else the bridge is not needed, I am right?

As I understood from the docs, this can be checked by checking if there is a query param "_storyblok" present in the URL.

Since the storyblok astro integration is initialised in the setup step of astro, I think it is currently not possible to have this "bridge" config option dynamic based on the request, correct?

Is there another way to achieve this?
Or coult the Astro storyblok integration be extended to achieve this?

### Suggested solution or improvement

Add an additional option parameter for the bridge option to enable the bridge only being loaded/initialised when page is loaded in the storyblok editor.

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by manuelschroederdev** [comment]
Hi @dominik-erni,

for now, I would suggest setting up two different deployments and conditionally loading the bridge via an environment variable.
I'm not sure if your idea (which is cool!) can be realized, as the Astro config is processed before runtime. I'll look into it though. 🙂
