### ISSUE TITLE
Unable to static build on production

### ISSUE THREAD

**Issue by fibtx** [storyblok/storyblok-astro#61]
Hi, I am getting this error when i try to build my app anywhere but not the localhost. On localhost everything works fine. However when i tried to build the app on Cloudflare pages or Github Workflow I always get this error. Could you please help me how to solve this?

[vite-plugin-storyblok] Could not load virtual:storyblok-components (imported by node_modules/@storyblok/astro/StoryblokComponent.astro): Cannot destructure property 'id' of '(intermediate value)' as it is null.

Thank you.

**Comment by manuelschroederdev** [comment]
Hey @fibtx,

thank you for your message. Could you please provide a minimal reproducible example of your code? I'll look into it asap.

**Comment by fibtx** [comment]
Hello, It still does not work for me :(. Any updates on this? I really need this to work, I will try to create reproduction repository next week if it helps.

**Comment by manuelschroederdev** [comment]
Hey @fibtx, I got an email notification about your earlier message, but now I see the issue has been closed. Did everything work out? 🙂
