### ISSUE TITLE
storyblokApiInstance has not been initialized correctly

### ISSUE THREAD

**Issue by MKlblangenois** [storyblok/storyblok-astro#616]
### Describe the issue you're facing

I'm getting the error "storyblokApiInstance has not been initialized correctly" in console.log on each page of the site
![image](https://github.com/storyblok/storyblok-astro/assets/42929225/8f0bb53c-17ed-4041-b38c-9e432c5bbe50)

### Reproduction

https://astro-espacedupossible-git-feature-canary-110-mediakod.vercel.app/

### Steps to reproduce

1. Install @storyblok/astro
2. Create a client for Storyblok
```typescript
import { StoryblokClient, useStoryblokApi } from "@storyblok/astro";

/**
 * The Storyblok client.
 *
 * @type {StoryblokClient}
 *
 * @since 0.0.1
 */
export const client: StoryblokClient = useStoryblokApi();
```
3. Use it to generate static paths
```typescript
# lib/storyblok/query.ts
/**
 * Get all Storyblok stories.
 *
 * @param {ISbStoriesParams} [filters={}]
 * @return {any} The Storyblok stories.
 */
export const getStories = async (filters: ISbStoriesParams = {}) => {
	const params: ISbStoriesParams = {
		version: "draft",
		token: import.meta.env.PUBLIC_STORYBLOK_TOKEN,
		resolve_relations: ["post.categories"],
		cv: +new Date(),
		...filters,
	};

	try {
		const { data } = await client.get("cdn/stories", params);

		return data?.stories || false;
	} catch (error) {
		console.error(error);
	}

	return false;
};
```

```astro
# pages/[folder]/[...page].astro

---
import { createPagination, getStories, getStory } from "../../lib/storyblok";

export const getStaticPaths = async () => {
	const stories = await getStories();

	if (!stories) {
		return {
			notFound: true,
		};
	}

      ...
```

Here's my `astro.config.mjs`:

```mjs
storyblok({
	accessToken: import.meta.env.PUBLIC_STORYBLOK_TOKEN ?? process.env.PUBLIC_STORYBLOK_TOKEN,
	components,
	apiOptions: {
		region: "eu",
		version: "draft",
		cache: {
			clear: "auto",
			type: "memory",
		},
		resolve_relations: ["post.categories"],
	},
	customFallbackComponent: "components/sections/sectionEmpty/index",
	enableFallbackComponent: true,
	bridge: true,
}),
```

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 683.45 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Brave Browser: 120.1.61.109
    Safari: 17.0
```

### Used Package Manager

npm

### Error logs (Optional)

storyblokApiInstance has not been initialized correctly

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by samducker** [comment]
Hi is there any update on this issue, I am facing the same. How can we disable this log. My storyblok integration is working fine I just don't want this log.

**Comment by dipankarmaikap** [comment]
Hi @samducker
I'm unable to reproduce the error on my end. Could you please provide a code repository or steps to help me better understand and investigate the issue?
