### ISSUE TITLE
Support deeper url structure with Dynamic Routing setup

### ISSUE THREAD

**Issue by dennis-NS** [storyblok/storyblok-astro#689]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

---

## Expected Behavior

When i go to url.com/company/hiring i expect it to render that story

## Current Behavior

It throws an error: `Expected "slug" to match "[^\/#\?]+?", but got "company/hiring"`

## Steps to Reproduce

1. Implement the dynamic routing found as in the readme
2. In Storyblok make a story with a deeper url structure eg: company/hiring
3. In your browser go to any route that would hit the `[slug].astro` file and see the error

**Comment by schabibi1** [comment]
@dennis-NS Please try with `src/pages/[...slug].astro` . I assume you need to use rest pareneter for such routing. See [docs from Astro](https://docs.astro.build/en/guides/routing/#rest-parameters) for more.

I recommend you to try out [Storyblok Astro Ultimate Tutorial series](https://www.storyblok.com/tp/the-storyblok-astro-ultimate-tutorial) with hands-on examples.
The first tutorial, ["Add a headless CMS to Astro in 5 minutes"](https://www.storyblok.com/tp/add-a-headless-cms-to-astro-in-5-minutes) solves your question.

**Comment by dennis-NS** [comment]
@schabibi1 ah wow such an easy fixed i missed out on! Thanks! Should this not be default in the readme/example/docs? Since this covers every use case and people won't make this mistake again in the future.
