### ISSUE TITLE
renderRichText not rendering anchors on URLs when using custom schema

### ISSUE THREAD

**Issue by mhagendoorn-9292** [storyblok/storyblok-astro#842]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

When adding a anchor to a Rich Text URL, the anchor isn't added to the URL. This only occurs when using a customSchema for `SbRichTextOptions`.

---

## Expected Behavior
Anchor gets added at the end of the URL

## Current Behavior
Anchor does not get added at the end of the URL

## Steps to Reproduce

1. Create a URL in a Rich Text field, add a anchor
![afbeelding](https://github.com/storyblok/storyblok-astro/assets/75429923/9591cad7-37ed-49c3-8248-5e12fd7c89c6)

2. Parse the content via `renderRichText` in `@storyblok/astro`
3. See that the response does not include the anchor at the end of the URL

Example:

```ts
---
import type { ISbRichtext, SbRichTextOptions } from "@storyblok/astro";
import { renderRichText, RichTextSchema } from "@storyblok/astro";
import cloneDeep from "lodash-es/cloneDeep";
import type { ISbNode } from "@storyblok/js";

const customSchema = cloneDeep(RichTextSchema);

customSchema.marks.link = (node: ISbNode) => ({
  tag: [
    {
      ...node,
      tag: "a",
      attrs: {
        ...node.attrs,
        href: node.attrs.href // We do some sanitation here
      },
    },
  ],
});

const options: SbRichTextOptions = { schema: customSchema };

const result = renderRichText(
  {
    type: "paragraph",
    content: [
      {
        type: "paragraph",
        content: [
          {
            text: "Link with anchor",
            type: "text",
            marks: [
              {
                type: "link",
                attrs: {
                  href: "/internal/test-mike-contentpage",
                  uuid: "b0b193a0-5c6a-4022-b9f6-cdd5d6cacbbe",
                  anchor: "test-anchor",
                  target: "_self",
                  linktype: "story",
                  story: [Object],
                },
              },
            ],
          },
        ],
      },
    ],
  },
  options
);
---
```

Since I'm spreading the `...node.attrs` in the `customSchema.marks.link`, the `anchor` property _is_ added to the `customSchema.marks.link`, so I would expect it to work. 

The above code gives the following `result`: 

```html
<p>
   <a href="/internal/test-mike-contentpage">Link with anchor</a>
</p>
```

When I remove the `customSchema.marks.link`, it results in following. The anchor gets added, as expected.

```html
<p>
   <a href="/internal/test-mike-contentpage#test-anchor">Link with anchor</a>
</p>
```

**Comment by dipankarmaikap** [comment]
Hi @mhagendoorn-9292 ,

Thank you for your question.

Based on your example code:

```javascript
mySchema.marks.link = (node: ISbNode) => {
  // ...
};
```

This replaces the default internal links logic. Essentially, you'll need to rewrite the link logic yourself. Here’s an example of how you can do it:

```javascript
mySchema.marks.link = (node: ISbNode) => {
  const attrs = { ...node.attrs };
  delete attrs.linktype;
  if (attrs.href) {
    // Do your sanitation here
    attrs.href = node.attrs.href;
  }
  // Handle email links and other possible logic
  if (attrs.anchor) {
    attrs.href = `${attrs.href}#${attrs.anchor}`;
    delete attrs.anchor;
  }
  if (attrs.custom) {
    for (const key in attrs.custom) {
      attrs[key] = attrs.custom[key];
    }
    delete attrs.custom;
  }
  return {
    tag: [
      {
        tag: "a",
        attrs: attrs,
      },
    ],
  };
};
```

You can also refer to the complete node's schema here: [Storyblok JS Client Schema](https://github.com/storyblok/storyblok-js-client/blob/main/src/schema.ts#L134C1-L173C2).

Let me know if you have any further questions.

**Comment by dipankarmaikap** [comment]
Hi @mhagendoorn-9292,

Since we haven’t received a response, we’re closing this issue for now. If you have any new information, please feel free to reopen it or create a new issue.

Thanks!
