### ISSUE TITLE
[BUG:NO LOADER] No loader is configured for ".html" And ".node"

### ISSUE THREAD

**Issue by JakiChen** [storyblok/storyblok-astro#844]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

---

## Expected Behavior

```dash
 astro  v4.11.0 ready in 1484 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

12:15:51 watching for file changes...
✘ [ERROR] No loader is configured for ".html" files: node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html

    node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:86:21:
      86 │       return require('./' + command)(self, argvx, callback);
         ╵                      ~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "mock-aws-s3"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:43:28:
      43 │     const AWSMock = require('mock-aws-s3');
         ╵                             ~~~~~~~~~~~~~

  You can mark the path "mock-aws-s3" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle. You can also surround this "require" call
  with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "aws-sdk"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:76:22:
      76 │   const AWS = require('aws-sdk');
         ╵                       ~~~~~~~~~

  You can mark the path "aws-sdk" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also surround this "require" call with
  a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "nock"

    node_modules/@mapbox/node-pre-gyp/lib/util/s3_setup.js:112:23:
      112 │   const nock = require('nock');
          ╵                        ~~~~~~

  You can mark the path "nock" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also surround this "require" call with
  a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] No loader is configured for ".node" files: node_modules/fsevents/fsevents.node

    node_modules/fsevents/fsevents.js:13:23:
      13 │ const Native = require("./fsevents.node");
         ╵                        ~~~~~~~~~~~~~~~~~

```

## Current Behavior

I imported the vite configuration from outside, and now I find that the following configuration can solve the error problem that occurs occasionally in development mode and then persists.

`config/vite.config.js` 

``` js
import { defineConfig } from 'vite';

import glsl from 'vite-plugin-glsl';

export default defineConfig({
 optimizeDeps: { exclude: ['@mapbox/node-pre-gyp','fsevents'] }, // add this solve
})
```

When executing `yarn build`, everything is normal.

> So my question is, what causes this? And does it have any impact on the project? Can this problem be solved in the inheritance in the end?

:-) I am a novice in writing code with the help of AI, and I am in the nascent stage.
## Steps to Reproduce

`astro.config.mjs`

```js
import { defineConfig } from 'astro/config';
import { siteUrl, vite, config, stbConfig } from './config';

// https://astro.build/config
export default defineConfig({
  site: siteUrl,
  i18n: {
    defaultLocale: 'zh-CN',
    locales: ['zh-CN', 'en'],
  },
  //
  outDir: 'build',
  build: {
    assets: 'assets',
    // assetsPrefix: siteUrl,
    inlineStylesheets: 'never',
  },
  compressHTML: import.meta.env.PROD,
  scopedStyleStrategy: 'attribute',
  //
  vite: vite,
  //
  ...(await import('./config/ssr/vercel/hybrid')).default,
  //
  integrations: [...config.integrations, ...stbConfig.integrations],
});

```

`config/storyblok.js`

```js
import { defineConfig } from 'astro/config';
import storyblok from '@storyblok/astro';

import { loadEnv } from 'vite';
const env = loadEnv('', process.cwd(), '');

export default defineConfig({
  integrations: [
    storyblok({
      accessToken: env.STORYBLOK_TOKEN,
      components: {
        // default
        feature: 'storyblok/Feature',
        grid: 'storyblok/Grid',
        page: 'storyblok/Page',
        teaser: 'storyblok/Teaser',
        //
        blogPost: 'storyblok/BlogPost',
        blogPostList: 'storyblok/BlogPostList',
      },
      apiOptions: {
        /**
         * eu（默认）：适用于在欧盟创建的空间
         * us：适用于在美国创建的空间
         * ap：适用于在澳大利亚创建的空间
         * ca：适用于在加拿大创建的空间
         * cn：针对在中国创建的空间 (容易 `401` 貌似不稳定)
         */
        region: 'eu',
      },
    }),
  ],
});
```

**Comment by schabibi1** [comment]
Hi @JakiChen 
We'll investigate this issue.

Meanwhile, the error logs you received are all from third parties. The issues are most likely separated from our @storyblok/astro SDK.

Could you try disabling the third-party package-related code and see if you still receive the same errors?
This will narrow down the issues and help spot which package and the configuration or the package-related code is causing the issue.

**Comment by schabibi1** [comment]
I'm closing it for now as I see the issues are more coming from the third party packages.
Please feel free to reopen the issue if you still have the same issue after you try out what I responded to and if it's from our SDK.

**Comment by schabibi1** [comment]
@JakiChen Thanks for the additional info. As you excluded the 3rd-party dependencies with [optimizeDeps.exclude](https://vitejs.dev/config/dep-optimization-options#optimizedeps-exclude), you excluded [@mapbox/node-pre-gyp](https://github.com/mapbox/node-pre-gyp), a third-party package from pre-building.

This is why it solves the error you got. You were already trying the initial request from my side to disable the third-party packages from dependencies.

I hope it answers your original question. Please feel free to ask if anything is not clear.

**Comment by JakiChen** [comment]
Hi, @schabibi1 

Forgive me, I am a novice who relies on AI to write JavaScript.

**What I want to know is why this bug occurs when using `storyblok`, but everything works fine without it. And the only thing involved in rendering in the entire project is `storyblok`, and the others are regular dependencies of the projec**t.

Here is the `package.json` of the storyblok boilerplate I made:

```json
{
  "private": true,
  "name": "astro-storyblok-starter",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "keywords": [
    "astro",
    "storyblok",
    "https",
    "vercel",
    "glsl",
    "three.js",
    "i18n"
  ],
  "dependencies": {
    "dayjs": "^1.11.12"
  },
  "devDependencies": {
    "@astrojs/check": "^0.8.3",
    "@astrojs/sitemap": "^3.1.6",
    "@astrojs/vercel": "^7.7.2",
    "@fullhuman/postcss-purgecss": "^6.0.0",
    "@storyblok/astro": "^5.0.0",
    "astro": "^4.12.2",
    "astro-robots": "^2.0.1",
    "autoprefixer": "^10.4.19",
    "cssnano": "^7.0.4",
    "sass": "^1.77.8",
    "typescript": "^5.5.4",
    "vite-plugin-glsl": "^1.3.0"
  }
}
```

If there is no other valuable reference information, just ignore it. I don’t have a project that deeply integrates storyblok to experience its elegance (I hope storyblok can get better and better. For example, I feel that the rich text editor is not as good as CKEditor at present).
