### ISSUE TITLE
The ability to use `resolve_links` in Storyblok Bridge

### ISSUE THREAD

**Issue by DMouayad** [storyblok/storyblok-astro#882]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-astro

[![storyblok.com](https://a.storyblok.com/f/88751/1500x500/7974d6bc34/storyblok-astro.png)][storyblokurl]

---

## Expected Behavior

I'm trying to find a way to have a text field that we can assign to it a link (the actual path - slug ) to a Story.
After looking for a solution, I found there's a way to do this with a Link field and
"resolve_links" option to get desired info (mainly the url - ful slug).

## Current Behavior

Now the docs mentions this:

> resolveRelations and resolveLinks will not have any effect in Astro, since the Storyblok Bridge is configured to reload the page. Thus, all the requests needed will be performed after the reload.

which is understandable but it also mentions the following:

> The provided options will be used when initializing the Storyblok Bridge.

MY QUESTION is:
Will we be able to use resolve_links or resolve_relations if it was provided in the bridge options??
I've already tried it but it didn't work.

what i tired:

`storyblok({
        bridge: {
            resolveLinks: "url"
        }, ....
  }) `

---

Thanks for ur amazing work & any help is much appreciated.

**Comment by DMouayad** [comment]
I'm sorry but it seems I didn't notice that changes weren't published.
After publishing All working as expected and I'm receiving the correct data response.

**Comment by mediabeastnz** [comment]
It would be handy if we could use resolve_links when using useStoryblok(). Even if it doesn't work for live previews but worked when a page is rendered.

**Comment by DMouayad** [comment]
> It would be handy if we could use resolve_links when using useStoryblok(). Even if it doesn't work for live previews but worked when a page is rendered.

I've yet to try if it works in live preview, BUT both `resolve_links` and `resolve_relations` are working for me with `storyblokApi.get()` in SSG.

**Comment by samducker** [comment]
Hi we should be able to pass params like resolve_links to live preview @DMouayad
